### ISSUE TITLE
I want to know where ''000821_result.npz'' files  exists.

### ISSUE THREAD

**Issue by jisoo920** [Cogito2012/UString#15]
hi guys 

I got an error while running the demo.sh.

so I want to know where ''000821_result.npz'' files exist.

```
Traceback (most recent call last):
  File "demo.py", line 352, in <module>
    all_results = np.load(p.result_file, allow_pickle=True)
  File "/home/gpuadmin/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'demo/000821_result.npz'
Saved in: demo/000821_vis.avi
```

thank for your time

**Comment by Cogito2012** [comment]
You may need to check if the result npz file is generated or not before running the result visualization.
